name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_GITHUB }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_GITHUB }}
          aws-region: eu-central-1
          
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.27.0

      - name: Decode kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_STAGING }}" | base64 -d > $HOME/.kube/config

      - name: Generate secrets.yaml
        run: |
          mkdir -p kube-config/staging
          {
            echo "apiVersion: v1"
            echo "kind: Secret"
            echo "metadata:"
            echo "  name: user-secrets"
            echo "type: Opaque"
            echo "data:"
            echo "  PII_DB_URL_KZ: $(echo -n '${{ secrets.PII_DB_URL_KZ }}' | base64)"
            echo "  CLINICAL_DB_URL_KZ: $(echo -n '${{ secrets.CLINICAL_DB_URL_KZ }}' | base64)"
            echo "  PII_DB_URL_PL: $(echo -n '${{ secrets.PII_DB_URL_PL }}' | base64)"
            echo "  CLINICAL_DB_URL_PL: $(echo -n '${{ secrets.CLINICAL_DB_URL_PL }}' | base64)"
            echo "  MASTER_DB_URL: $(echo -n '${{ secrets.MASTER_DB_URL }}' | base64)"
            echo "  JWT_KEY: $(echo -n '${{ secrets.JWT_KEY }}' | base64)"
            echo "  AWS_ACCESS_KEY_ID: $(echo -n '${{ secrets.AWS_ACCESS_KEY_ID }}' | base64)"
            echo "  AWS_SECRET_ACCESS_KEY: $(echo -n '${{ secrets.AWS_SECRET_ACCESS_KEY }}' | base64)"
            echo "  AWS_REGION: $(echo -n '${{ secrets.AWS_REGION }}' | base64)"
            echo "  AWS_BUCKET_NAME: $(echo -n '${{ secrets.AWS_BUCKET_NAME }}' | base64)"
            echo "  TWILIO_ACCOUNT_SID: $(echo -n '${{ secrets.TWILIO_ACCOUNT_SID }}' | base64)"
            echo "  TWILIO_AUTH_TOKEN: $(echo -n '${{ secrets.TWILIO_AUTH_TOKEN }}' | base64)"
            echo "  TWILIO_API_SID: $(echo -n '${{ secrets.TWILIO_API_SID }}' | base64)"
            echo "  TWILIO_API_SECRET: $(echo -n '${{ secrets.TWILIO_API_SECRET }}' | base64)"
            echo "  RECAPTCHA_SECRET_KEY: $(echo -n '${{ secrets.RECAPTCHA_SECRET_KEY }}' | base64)"
          } > kube-config/staging/secrets.yaml

      - name: Deploy to Kubernetes
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh staging deploy